steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--build-arg', 'DATABASE_URL=${_DATABASE_URL}',
      '--build-arg', 'AUTH_SECRET=${_AUTH_SECRET}',
      '--build-arg', 'NEXT_PUBLIC_API_BASE_URL=${_NEXT_PUBLIC_API_BASE_URL}',
      '--build-arg', 'RESEND_API_KEY=${_RESEND_API_KEY}',
      '-t', 'gcr.io/$PROJECT_ID/web-app:$COMMIT_SHA',
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/web-app:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'web-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/web-app:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NODE_ENV=production,DATABASE_URL=${_DATABASE_URL},AUTH_SECRET=${_AUTH_SECRET},NEXT_PUBLIC_API_BASE_URL=${_NEXT_PUBLIC_API_BASE_URL},RESEND_API_KEY=${_RESEND_API_KEY}'

images:
  - 'gcr.io/$PROJECT_ID/web-app:$COMMIT_SHA'

substitutions:
  _DATABASE_URL: ''
  _AUTH_SECRET: ''
  _NEXT_PUBLIC_API_BASE_URL: ''
  _RESEND_API_KEY: ''