import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import { StoreProvider } from "@/context/store-context";
import { auth } from "./api/auth/[...nextauth]";
import { AppProvider } from "@/lib/app-provider";

import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <StoreProvider>
            <AppProvider>
              <Toaster />
              {children}
            </AppProvider>
          </StoreProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
