steps:
  # Install pnpm
  - name: 'node:18'
    entrypoint: npm
    args: ['install', '-g', 'pnpm@9.14.2']

  # Install dependencies
  - name: 'node:18'
    entrypoint: pnpm
    args: ['install', '--frozen-lockfile']

  # Generate Prisma Client
  - name: 'node:18'
    entrypoint: pnpm
    args: ['prisma', 'generate']
    dir: 'apps/server'
    
  # Build the project
  - name: 'node:18'
    entrypoint: pnpm
    args: ['build']
    env:
      - 'NODE_ENV=production'
    
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/server-app:$COMMIT_SHA',
      '.'
    ]
    
  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/server-app:$COMMIT_SHA']
    
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'server-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/server-app:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NODE_ENV=production'

images:
  - 'gcr.io/$PROJECT_ID/server-app:$COMMIT_SHA'

timeout: '1800s'